name: "Frogbot Scan and Fix"
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  create-fix-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start FastCI Optimization
        uses: jfrog-fastci/fastci@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fastci_otel_token: ${{ secrets.FASTCI_TOKEN }}

      # Install prerequisites
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - uses: jfrog/frogbot@v2
        env:
          # [Mandatory]
          # JFrog platform URL
          JF_URL: ${{ secrets.FROGBOT_URL }}

          # [Mandatory if JF_USER and JF_PASSWORD are not provided]
          # JFrog access token with 'read' permissions on Xray service
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}

          # [Mandatory]
          # The GitHub token automatically generated for the job
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
